language: node_js
node_js:
  - '8'
addons:
  apt:
    packages:
      - xvfb
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
  - yarn install --pure-lockfile

script:
  - yarn run tsc
  - yarn run lint
  - yarn run test